global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]

  # cAdvisor for container metrics
  - job_name: "cadvisor"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Example: Monitor sample application
  - job_name: "transfer-service-app"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["transfer_service:8000"]
  - job_name: "search-service-app"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["search_service:8001"]
